# Deployment for verifying that a cluster is set up correctly. Contains nginx container that listens for requests.
# See containerfile @https://github.com/clcollins/homelabCloudInit/blob/master/simpleCloudInitService/data/Containerfile
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-verify
  namespace: kube-verify
  labels:
    app: kube-verify
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kube-verify
  template:
    metadata:
      labels:
        app: kube-verify
    spec:
      containers:
      - name: nginx
        image: quay.io/clcollins/kube-verify:01
        ports:
        - containerPort: 8080
