apiVersion: v1
kind: ConfigMap
metadata:
  name: es-config
  namespace: elk
data:
  elasticsearch.yml: |
    cluster.name: "es-k8s-cluster"
    node.name: ${HOSTNAME}
    #node.data: true # dep
    discovery.seed_hosts: ["localhost", "127.0.0.1", "elasticsearch", ${HOSTNAME}]
    #node.master: true   # Deprecated in 7.x
    network.host: "0.0.0.0"
    bootstrap.memory_lock: false
    #discovery.zen.ping.unicast.hosts: elasticsearch-cluster
    #discovery.zen.minimum_master_nodes: 1
    xpack.security.enabled: false
    #xpack.monitoring.enabled: false
  ES_JAVA_OPTS: -Xms512m -Xmx512m
  
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: es
  namespace: elk
  labels:
    component: elasticsearch
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: elasticsearch
    spec:
      serviceAccount: elasticsearch
      initContainers:
      - name: init-sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
      - name: es
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
                #image: quay.io/pires/docker-elasticsearch-kubernetes:5.6.2
        image: elasticsearch:7.9.3
        env:
        - name: ES_JAVA_OPTS
          valueFrom:
              configMapKeyRef:
                  name: es-config
                  key: ES_JAVA_OPTS
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: "DISCOVERY_SERVICE"
          value: "elasticsearch"
        - name: NODE_MASTER
          value: "true"
        - name: NODE_DATA
          value: "true"
        - name: HTTP_ENABLE
          value: "true"
        - name: "cluster.name"
          value: "es-k8s-cluster"
        - name: "network.host"
          value: "0.0.0.0"
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - mountPath: /data
          name: es-storage
        - name: elasticsearch-config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
      volumes:
      - name: es-storage
        emptyDir: {}
      - name: elasticsearch-config
        configMap:
          name: es-config
          items:
            - key: elasticsearch.yml
              path: elasticsearch.yml
